In [1]:
import pandas as pd


In [2]:
pd.__version__

'2.3.1'

In [3]:
wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv


SyntaxError: invalid syntax (4180089282.py, line 1)

In [4]:
import numpy as np

In [5]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.full(18,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
np.full((2,2),1)

array([[1, 1],
       [1, 1]])

In [20]:
a = np.array([1,2,3,4,5])

In [22]:
a

array([1, 2, 3, 4, 5])

In [24]:
a[1]=3

In [25]:
a

array([1, 3, 3, 4, 5])

In [31]:
np.arange(4,81)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79, 80])

In [34]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]
 
columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]
 

In [36]:
df = pd.DataFrame(data)


In [37]:
df

0         1     2      3  4          5            6      7
0   Nissan    Stanza  1991  138.0  4     MANUAL        sedan   2000
1  Hyundai    Sonata  2017    NaN  4  AUTOMATIC        Sedan  27150
2    Lotus     Elise  2010  218.0  4     MANUAL  convertible  54990
3      GMC    Acadia  2017  194.0  4  AUTOMATIC      4dr SUV  34450
4   Nissan  Frontier  2017  261.0  6     MANUAL       Pickup  32340

In [46]:
df = pd.DataFrame(data, columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [47]:
df.head(n=2)

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150

In [48]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [50]:
df=pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [53]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [54]:
len(df.index)

9704

In [55]:
df['fuel_type']

0       Gasoline
1       Gasoline
2       Gasoline
3         Diesel
4       Gasoline
          ...   
9699      Diesel
9700    Gasoline
9701      Diesel
9702      Diesel
9703      Diesel
Name: fuel_type, Length: 9704, dtype: object

In [57]:
df.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

In [60]:
df.groupby('fuel_type').sum()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
fuel_type                                                                   
Diesel                  957650        18170.0    667161.0    1.443690e+07   
Gasoline                980320        18372.0    679156.0    1.468753e+07   

           acceleration  model_year  \
fuel_type                             
Diesel          65384.6     9667095   
Gasoline        66417.8     9852346   

                                                      origin  \
fuel_type                                                      
Diesel     USAUSAAsiaEuropeUSAAsiaEuropeAsiaEuropeUSAEuro...   
Gasoline   EuropeUSAEuropeEuropeEuropeUSAUSAUSAEuropeEuro...   

                                                  drivetrain  num_doors  \
fuel_type                                                                 
Diesel     All-wheel driveAll-wheel driveFront-wheel driv...      -77.0   
Gasoline   All-wheel driveFront-wheel driveFront-wheel dr...       18.0   

           fuel_efficiency_mpg  
fuel_type                       
Diesel            71965.634626  
Gasoline          73451.165661

In [62]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [70]:
df['fuel_efficiency_mpg'].max()

np.float64(25.96722204888372)

In [81]:
df.groupby('origin').sum()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
origin                                                                   
Asia                 649570        12428.0    452864.0    9.761431e+06   
Europe               648640        11864.0    448912.0    9.782848e+06   
USA                  639760        12250.0    444541.0    9.580152e+06   

        acceleration  model_year  \
origin                             
Asia         44102.8     6531306   
Europe       44352.1     6545402   
USA          43347.5     6442733   

                                                fuel_type  \
origin                                                      
Asia    DieselDieselDieselGasolineGasolineDieselGasoli...   
Europe  GasolineGasolineGasolineGasolineDieselDieselDi...   
USA     GasolineDieselGasolineDieselGasolineDieselGaso...   

                                               drivetrain  num_doors  \
origin                                                                 
Asia    Front-wheel driveAll-wheel driveAll-wheel driv...       -5.0   
Europe  All-wheel driveFront-wheel driveAll-wheel driv...       31.0   
USA     Front-wheel driveAll-wheel driveFront-wheel dr...      -85.0   

        fuel_efficiency_mpg  
origin                       
Asia           48620.027628  
Europe         48623.000179  
USA            48173.772479

In [82]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [89]:
df_1 = df[df['origin']== 'Asia']

In [90]:
df_1

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [92]:
df_1['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [94]:
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [93]:
df['horsepower'].median()

np.float64(149.0)

In [96]:
df['horsepower'].isnull().sum()

np.int64(708)

In [97]:
df_2 = df.horsepower.values

In [98]:
df_2

array([159.,  97.,  78., ..., 138., 177., 140.], shape=(9704,))

In [102]:
df_2=np.nan_to_num(df_2, copy=True, nan=152, posinf=None, neginf=None)

In [105]:
np.median(df_2)

np.float64(152.0)

In [106]:
df_1

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [111]:
df_3 = df_1[['vehicle_weight','model_year']]

In [119]:
x = df_3.head(n=7)

In [121]:
x = x.values

In [122]:
x.shape

(7, 2)

In [124]:
xt=np.matrix_transpose(x)

In [130]:
xt.shape

(2, 7)

In [125]:
xtx = np.matmul(xt,x)

In [126]:
xtx.shape

(2, 2)

In [128]:
x_inv = np.linalg.inv(xtx)

In [129]:

y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [131]:
z = np.matmul(x_inv, xt)

In [133]:
w=np.matmul(z,y)

In [135]:
w.sum()

np.float64(0.5187709081074016)